<a href="https://colab.research.google.com/github/rxg95600/Neural-Network-Assignment-ICP_2/blob/main/700759560_RAMAKRISHNA_GANTA_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**QUESTION-1**

---


In [14]:
# employee class code in Python
# class definition

class Employee:

    # data member to count the number of Employees
    count_of_employees = 0
    __name=""
    __family=""
    __salary=0
    __department=""

    # function to set data
    # constructor to intiliaze the name, family, salary, department
    def __init__(self, name, family, salary, department):
        self.__name = name
        self.__family = family
        self.salary = salary
        self.__department = department
        Employee.count_of_employees += 1 #to count number of employees

    #function to calculate the average salary of an employee
    def average_salary(employees):
        total = 0
        for employee in employees:
            total += employee.salary
        return total / Employee.count_of_employees

    #displaying the details of an employee
    def showData(self):
        print("The count of an employee is:",Employee.count_of_employees)
        #print("The Name of an employee is\t:", self.__name)
        #print("The Family of an employee is\t:", self.__family)
        #print("The Department of an employee is\t:", self.__department)
        #print("The Salary of an employee is\t:", self.__salary)

#A subclass which is inherited the properties of the class
class FulltimeEmployee(Employee):
   #intiliazation
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


#main class
def main():
    employees = []
    one = FulltimeEmployee("RAMA KRISHNA", "fm-pothuru", 120000, "Enginner")  #Declaration
    employees.append(one)  #appending
    two = FulltimeEmployee("RAM", "fm-kamtam", 180000, "Developer")
    employees.append(two)
    three = Employee("KRISHNA", "fm-dhawswarala", 160000, "Manager")
    employees.append(three)
    four = Employee("RK", "Fm-siddavtam", 135000, "fashion")
    employees.append(four)
    Employee.showData(employees)  #showing the data of an employee
    print("Average salary of an employee is:", FulltimeEmployee.average_salary(employees)) #Average salary of an employee


if __name__ == "__main__":
    main()

The count of an employee is: 4
Average salary of an employee is: 148750.0


QUESTION-**2**

---



In [15]:
import numpy as np

#function to replace the maximum value in an array of axis x and y based on the condition
def replace_maxmium(array, replace_value, axis):
    result = np.where(array == np.max(
        array, axis=1).reshape(-1, 1), 0 * array, array)
    print(result)


def main():

 #creating a random vector of size 20 which is having in the range of 1-20
    rand20 = np.random.random_sample(20) * 20 + 1
    print(rand20)

    #reshaping the array to 4 by 5 in random20
    rand20_4by5 = rand20.reshape((4, 5))
    print(rand20_4by5)

    replace_maxmium(rand20_4by5, 0, 1)#replacing the max value in each row by zero


if __name__ == "__main__":
    main()

[18.59917886 17.93776136 20.29872473 10.03574385 17.74173013  1.26614772
  2.45905661  6.01446272  6.36379688  7.33274868  8.06460007 11.02099009
 14.18561718  9.05107114 16.24876697  2.32607611 16.22672296 15.75924705
 18.41589837 14.64476458]
[[18.59917886 17.93776136 20.29872473 10.03574385 17.74173013]
 [ 1.26614772  2.45905661  6.01446272  6.36379688  7.33274868]
 [ 8.06460007 11.02099009 14.18561718  9.05107114 16.24876697]
 [ 2.32607611 16.22672296 15.75924705 18.41589837 14.64476458]]
[[18.59917886 17.93776136  0.         10.03574385 17.74173013]
 [ 1.26614772  2.45905661  6.01446272  6.36379688  0.        ]
 [ 8.06460007 11.02099009 14.18561718  9.05107114  0.        ]
 [ 2.32607611 16.22672296 15.75924705  0.         14.64476458]]
